### ISSUE TITLE
Can't import smbus

### ISSUE THREAD

**Issue by PhilG1300** [T-622/RPI-PICO-I2C-LCD#1]
Hello,
Just trying your code for driving 16x2 LCD on Raspberry Pi Pico using Micropython.
Have followed your instructions and copied the files onto the Pico.
Edited the parameters and when I try to run I get and error when the code tries to 
import smbus

If I run this from the command prompt the inbuilt library is not found.
Please advise.
Regards
Phil Green

**Comment by T-622** [comment]
Can you tell me what params you edited?
#1) Make sure the right .UF2 file is on the pico
#2) How are you running the code? Thonny or something else?
#3) Make sure python is installed properly to ensure the right libraries are there
#4) Try renaming the pico_i2c_lcd_test.py to main.py to ensure the right file runs

How are you running this code? Maybe there is a better alternative. Please upload a screenshot of the error so I can understand this better.

Thanks
Tyler Peppy

**Comment by PhilG1300** [comment]
Hello Tyler,
Thanks for the prompt reply.

I am using Micropython version 1.14 for the Raspberry Pi Pico

Running code via Thonny which is the current version

even when running from an Terminal program direct to the Pico I see:-

MPY: soft reboot
MicroPython v1.14 on 2021-02-13; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>> import smbus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'smbus'
>>> 

So I think the module is missing in the Micropython image I programmed into the Pico?

I have other code working fine with I2C but they do not use the smbus library.

Regards
Phil

**Comment by T-622** [comment]
Currently, I do not know why that is being imported. I know that the RPI foundation released a newer firmware image recently. I would try with that. I attempted to import smbus manually through the REPL and that resulted in the exact same error you are getting. Normally I open the 3 files in Thonny and from the top bar, click on the main program and the play button (Run program). I can continue to look into this issue for you but I think the new firmware image and reuploading all the program files is a good starting point!

All the best,
Tyler Peppy
