### ISSUE TITLE
 3 addresses for LCD issue 

### ISSUE THREAD

**Issue by Domingmr** [T-622/RPI-PICO-I2C-LCD#10]
Hello,

 I have some minor issues with using the scan.py as well as getting anything loaded onto the LCD screen.
I was going to post a screenshot, but github isn't allowing that at this time for some reason.
Upon running the scan.py script, I receive an array for the LCD address as follows in HEX:
[62, 96, 112]
and converted to decimal with make it 
[3E, 60, 70]
This is strange as there should only be one address.
Either way, through troubleshooting, all 3 values work, if used separately, in the test.py script, as it runs and goes each line of testing script for the LCD, but the LCD doesn't illuminate or anything.
If the whole array is used, an error message occurs. Please help on this matter. 3 addresses is strange, and no LCD illumination or messaging is not helping. Thank you.

-Dom

**Comment by Algester** [comment]
The 3 address might be due to your LCD backpack you may have to check the documentation on which pads short to make which address

Worst comes to worst you may need to state an address for the LCD API
