### ISSUE TITLE
Pico_I2C_Lcd Line 22 error

### ISSUE THREAD

**Issue by dadsgone0** [T-622/RPI-PICO-I2C-LCD#13]
Im having an issue iwth the Pico_I2C_Lcd file 
![image](https://user-images.githubusercontent.com/84343107/185209510-28a74b98-137c-42cb-8eb3-69bc33523daf.png)
II dont know how to fix this, can anyone help?

**Comment by T-622** [comment]
As the README indicated, this error is linked to a communication error between the Raspberry Pi Pico host and the I2C device. Even so, line 22 indicates `self.i2c.writeto(self.i2c_addr, bytes([0]))`, demonstrating that the code is attempting to write data to the I2C address, of which an error is thrown for the device not being reachable. To diagnose this, I need more detail on your current hardware setup (Images appreciated!).

**Comment by Acronychal** [comment]
Hi, I am having the same problem. Below is what i'm running:

`import utime
from machine import I2C
from lcd_api import LcdApi
from pico_i2c_lcd import I2cLcd

I2C_ADDR     = 0x27
I2C_NUM_ROWS = 2
I2C_NUM_COL  = 16

i2c = I2C(0, sda=machine.Pin(0), scl=machine.Pin(1), freq=400000)
lcd = I2cLcd(i2c, I2C_ADDR, I2C_NUM_ROWS, I2C_NUM_COL)

lcd.clear()
lcd.move_to(0,0)
lcd.putsrt('hello')
utime.sleep(2)
`

below is the set up. 
Pico W 
TMP117 by sparkfun
LCD1602 from a freenove kit

![pico-w-tmp117-lcd1602](https://user-images.githubusercontent.com/27730439/189821861-5024fc20-973a-499e-8e5c-71d288e9f708.png)

ERROR:

'>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "pico_i2c_lcd.py", line 22, in __init__
OSError: [Errno 5] EIO
>>> 
'
I'll test this same set up on a Pico and Pico H and report back with results at a later time.

**Comment by Acronychal** [comment]
> Hi, I am having the same problem. Below is what i'm running:
> 
> `import utime from machine import I2C from lcd_api import LcdApi from pico_i2c_lcd import I2cLcd
> 
> I2C_ADDR = 0x27 I2C_NUM_ROWS = 2 I2C_NUM_COL = 16
> 
> i2c = I2C(0, sda=machine.Pin(0), scl=machine.Pin(1), freq=400000) lcd = I2cLcd(i2c, I2C_ADDR, I2C_NUM_ROWS, I2C_NUM_COL)
> 
> lcd.clear() lcd.move_to(0,0) lcd.putstr('hello') utime.sleep(2) `
> 
> below is the set up. Pico W TMP117 by sparkfun LCD1602 from a freenove kit
> 
> ![pico-w-tmp117-lcd1602](https://user-images.githubusercontent.com/27730439/189821861-5024fc20-973a-499e-8e5c-71d288e9f708.png)
> 
> ERROR:
> 
> '>>> %Run -c $EDITOR_CONTENT Traceback (most recent call last): File "", line 11, in File "pico_i2c_lcd.py", line 22, in **init** OSError: [Errno 5] EIO
> 
> > > >
> 
> ' The error goes away on Pico and Pico H, but the display doesn't print anything.

I had the wrong setting on the trim pot, good ol layer 1. I was able to run the pico_i2c_lcd_test.py with no issue on Pico 2020 & Pico H. 

Same error on Pico W

**Comment by T-622** [comment]
I'm guessing that this is once again a signaling level issue, although I alluded to this in the README already. You can try to use a 2 1K resistors; one from +5V to the SCL pin, the other from +5V to the SDA pin. The external pullups should change the signalling voltage from +3.3V to +5V instead as I believe this is an issue.

**Comment by T-622** [comment]
It is also possible to put external pullups on the I2C backpack as there are pads for it.

**Comment by T-622** [comment]
I will try my own setup and get back to this when I have an answer.

**Comment by stkr22** [comment]
Stupid issue, the small screw on the backpack wasn't adjusted correctly. After turning it to the left the screen started and showed the test text.

**Comment by T-622** [comment]
Great! Glad it wotrks now. For future issues, people can refer to the README.
