### ISSUE TITLE
I get an error when running the test

### ISSUE THREAD

**Issue by 24-Bitcodes** [T-622/RPI-PICO-I2C-LCD#14]
I get this error while running the test (I know that my hexadecimal is correct.)
`
Traceback (most recent call last):
  File "<stdin>", line 62, in <module>
  File "<stdin>", line 16, in test_main
  File "pico_i2c_lcd.py", line 22, in __init__
OSError: [Errno 5] EIO`

How can I fix this?

**Comment by T-622** [comment]
As many have already demonstrated with the previous issues I've closed, this OSError 5 is a communication error. Please refer to previous closed issues. Generally, this is becuase the LCD is not getting enough power, or the SCL/SDA lines are reversed.
