### ISSUE TITLE
Cant import lcd_api or pico_i2C_lcd

### ISSUE THREAD

**Issue by KimCavendish** [T-622/RPI-PICO-I2C-LCD#2]
Hello,

I have copied the 3 files on to the pico. However Thonny returns ImportError: no module named "lcd_api" and no module named "pico_i2c_lcd"

What am I doing wrong ?

Best regards
Kim

**Comment by T-622** [comment]
Good day Kim, 
1.) Make sure no program is running on the pico then, in Thonny -> File -> Save Copy -> Raspberry Pi Pico. If it does not prompt you where to save it to, make sure the board is properly connected and that the right COM port is selected. Then hit the STOP button in thonny to kill all of the board's processes.
2.) As should be obvious, when you save the files to the pico, ensure you make sure the file name is the exact same as the file same. Normally, it would save another file but, as the imports at the top of the files require specific names, the programs saved require those exact names (Case sensitive). 
3.) Make sure the pico_i2c_lcd_test.py is run as opposed to any other file as the main. 
4.) Make sure the latest .uf2 firmware is flashed to the board by downloading it from [(](https://www.raspberrypi.org/documentation/pico/getting-started/static/f70cc2e37832cde5a107f6f2af06b4bc/rp2-pico-20210205-unstable-v1.14-8-g1f800cac3.uf2) then, holding the BOOTSEL button on the Pico and copying that downloaded file onto the pico which now looks like a flash drive!


Send me images of how the program is being uploaded and maybe I can further this if the issue still persists.

Thanks, 
Tyler Peppy

**Comment by KimCavendish** [comment]
Hi T-622,

Thank you for the help and the answer. However that did not change a thing. I still get the same errors. 

I load the programs exactly as you describe (Thonny -> File -> Save Copy -> Raspberry Pi Pico).  I get prompted to type in a file name (I paste "lcd_api etc. for the three files). I do not understand the difference/significance btw. "save as" and and "save copy" The seem to behave exactly the same. Isn´t the problem, that the "lcd_api" is not installed as a library. I dont have this problem with other installed libraries via "manage packages".

I am sorry for my stupidity ;o)

Best regards

Kim

**Comment by T-622** [comment]
Alright, to answer the question about the significance about the file names when loaded onto the Pico, they all need to be the exact same as their python file names. However, lcd_api is wrong. You need lcd_api.py rather (unless you are already adding the .py  extension to the file when you upload it to the board. At the time of running also, you must have all 3 files open in Thonny and only run the one I described as the substitute for a "main.py" file. I never installed it as a library on the Pico. I just copied all 3 files with their names and the .py extension when saving them to the Pico (Very important) and used the green play button on the main file to run that one manually. I do not know what the issue could be right now but I would give putting the .py extension to the files when you copy them to the Pico a try. If it still persists, we can try to wipe the Pico, update the firmware and then copy the files.

Best of luck,
Tyler Peppy
