### ISSUE TITLE
can you help please

### ISSUE THREAD

**Issue by markrharvey** [T-622/RPI-PICO-I2C-LCD#7]
hi im not sure what ive done wrong I followed each of your steps exactly but something is not quite right the screen comes on so it is definitely getting power however the cursor is not showing up and neither is any characters the screen is just flashing (turning on and off)

**Comment by T-622** [comment]
Hi Mark, it seems that the display is going through the set of tests written for it meaning, the data is being recieved and understood by the chip. This leaves 3 options for debugging; contrast adjustment (Fiddle with the potentiometer or blue box on the lcd's backpack), logic levels (are you using a level translator as described?) and finally, the lcd voltage (are you powering the LCD with 5v (VBUS pin as + pin #40) or 3.3v (3V3_OUT pin #36). You should be using 5V, with a level translator's low voltage side fed by 3.3v although, people have gotten this working without one. I would try rotating the contrast ADJ knob until charecters start showing up as like previously mentionned, the LCD seems to be doing the backlight and controller ON/OFF test in the sample code.

Best of luck,
Tyler Peppy

**Comment by oxicottin** [comment]
@markrharvey @T-622, I'm not trying to highjack your thread I have the same issue and wanted to know if and how you resolved this? I have a 4X20 display and am not using a level translator and have followed Tinkernuts video. I also get power and the only thing that I see the screen do is in Thonny when the code says screen on/off the LCD does it but as for text or anything else it doesnt do.  The LCD I purchase from Amazon...

[HiLetgo 2004 20X4 LCD](https://www.amazon.com/gp/product/B01DKETWO2/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1)

**Comment by T-622** [comment]
Ultimately, you can keep fiddling with the level shifters but you both have the correct hardware. You ultimately need an Oscilloscope to debug this one.

Keep on debugging,
Tyler

**Comment by markrharvey** [comment]
hey sorry but i cant get it to work at all anymore it keeps coming up with different errors now instead the screen lights up but none of the code work not even the scan to find the address of the screen 


import machine
sda = machine.Pin(0)
scl = machine.Pin(1)
i2c = machine.I2C(0,sda=sda,scl=scl, freq=400000)
print(i2c.scan())

this just replies with [] with nothing inside 

and when i try to run the test file this comes up



>>> %Run -c $EDITOR_CONTENT
Running test_main
Traceback (most recent call last):
  File "<stdin>", line 62, in <module>
  File "<stdin>", line 16, in test_main
  File "pico_i2c_lcd.py", line 22, in __init__
OSError: [Errno 5] EIO
>>> 

im not sure why this is happening now everything was working when i last put up the issue but i put it away and now ive got it back out to try to get it and now it seems like ive gone further back ratherthan heading forwards

**Comment by T-622** [comment]
Like I said already, OSERROR[5] is the code not being able to contact the specified I2C address. The reason that the main code won't work is becuase your I2C Scanner can't return anything meaning either there is a bad connection or a pin on the RP2040 is broken. What does your current setup look like for driving the LCD? What voltage are you using to power the LCD? Are you using level shifters?

**Comment by T-622** [comment]
I believe that this may be a sillicon issue or issue with your display. I would leave the default 0x27 address as this ADDR is what all the displays default to. Ultimately, you can also try a different pair of I2C pins like those on machine pin 3 and 4 {I2C1} (4 and 5 on pinout guide)

**Comment by T-622** [comment]
Make sure to change the code to use pins 3 and 4 too. Make sure they aren't using 0 and 1

**Comment by sushipan** [comment]
I also meet this issue , rotate the '+' with a screwdriver ,then you can see the out put !
